Feature/jc19 333 table view v1
saritasa-nest/camp-js-2022-eldar-abdrahmanov pull request #1
Opened 2022-07-13 04:12 UTC by EldrAbdr

2022-07-13 05:12 UTC, golovachev-yaroslav requested changes

2022-07-13 05:12 UTC, golovachev-yaroslav commented on apps/vanilla/src/components/animeCard.ts
> +  private getElement(parentElement: HTMLElement, selector: string): HTMLElement {
Please format jsdoc
```
/**
 * Checking if an element exists.
 * @param parentElement Looking for in this element.
 * @param selector The element selector we are looking for.
 */
```

2022-07-13 05:12 UTC, golovachev-yaroslav commented on apps/vanilla/src/components/constants/constants.ts
> +const SORT_BY_ID_URL = 'https://api.camp-js.saritasa.rocks/api/v1/anime/anime/?ordering=id';
The base url repeated many times, it would be better to move common part into a variable.

2022-07-13 05:12 UTC, golovachev-yaroslav commented on apps/vanilla/src/components/pagination/paginationCell.ts
> +  public cell: HTMLElement | undefined;
You can reduce
`public cell?: HTMLElement;`

2022-07-13 05:12 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.ts
> +import 'bootstrap/dist/css/bootstrap.min.css';
External libs should be imported as the first.

2022-07-13 05:12 UTC, golovachev-yaroslav commented on libs/core/mappers/anime.mapper.ts
> +    )
Please format the code
`})`

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa requested changes

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/blocks/anime-container/anime-container.css
> +  gap: 16px;*/
Please don't store commented code in repository.

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/blocks/active/activated.css
> +  color: cornflowerblue;
Prefer using variables for color values

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/blocks/anime-container/anime-container.css
> +  font-size: 18px;
Prefer using variables for font related values

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/animeCard.ts
> +    ) as HTMLElement;
Prefer using generics. Also you should omit type annotation because it would automatically inherited by typescript.
```suggestion
    const element = parentElement.querySelector<HTMLElement>(selector);
```

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/animeCard.ts
> +  private getElement(parentElement: HTMLElement, selector: string): HTMLElement {
You can make your function better by using generic. So instead of always returning HTMLElement it could return generic type.

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/animeTable/table.ts
> +   * @param element - HTML element.*/
Please properly format multiline jsdoc. For multiline jsdoc you should leave first and last lines empty, like so:
```suggestion
  /**
   * Render element.
   * @param element HTML element.
   */
```
Also you should omit `-` after params.

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/animeTable/tableHeaderButton.ts
> +    this.element = document.querySelector(id) as HTMLElement;
If I understand correctly you use assertion to get rid of `null`. I've seen `getElement` method in `AnimeCard`, you can make it global utility function and use it here and similar cases.

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/animeTable/tableHeaderButton.ts
> +  public clickHandler: () => void;
If you only initializing this properties in constructor and not mutating them anywhere else, you should make them readonly.

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/api.ts
> +    });
Please don't mix `await/async` and `.then`

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/pagination/pagination.ts
> +  public results?: Anime[] | null;
Don't forget about readonly for arrays.

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/pagination/paginationCell.ts
> +    if (!this.cell) {
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#dont-use-implicit-type-casting

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.ts
> +const animeTable: Table = new Table('#anime-container');
You should omit unnecessary type annotation.

2022-07-13 05:32 UTC, artem-sotnichenko-saritasa commented on libs/core/dtos/aired.dto.ts
> +  readonly end: string | Date;
You can't get Date object from the api.

2022-07-13 05:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/blocks/anime-container/anime-container.css
> +  grid-template-columns: repeat(3, 1fr);
Please remove unused code.

2022-07-13 05:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/animeCard.ts
> +  public readonly image: string;
It seems strange that image has string type, maybe rename to imageUrl to avoid misunderstanding?

2022-07-13 05:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/animeTable/tableHeaderButton.ts
> +      this.setButtonActive();
It seems strange that you call t`his.setButtonActive()` twice. And the third time inside `this.changeActiveStatus();`

2022-07-13 05:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/api.ts
> +  let pagination: Pagination = PaginationMapper.fromDto({ count: 0, next: '', previous: '', results: [] });
It seems strange for me calling mapper with empty values, maybe initialize by some default constant?

2022-07-13 05:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/pagination/pagination.ts
> +  public count: number;
Not clear what it is, please fix docs or names if it needs.

2022-07-13 05:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/pagination/pagination.ts
> +  public results?: Anime[] | null;
I think pagination class should be universal, not only for Anime instance.

2022-07-13 05:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/pages/index.ts
> +  25,
What is 25? Please use constant

2022-07-13 05:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/api.ts
> +export async function getPagination(url: string): Promise<Pagination> {
You should construct the url here, components shouldn't know anything about api.

2022-07-13 05:50 UTC, kristinaSvobodinaSaritasa commented on libs/core/models/pagination.ts
> +export class Pagination extends Immerable{
I don't understand why you describe Pagination class twice.

2022-07-13 16:05 UTC, maxineo commented on apps/vanilla/src/components/animeTable/tableHeaderButton.ts
> +    this.element.parentNode?.childNodes.forEach((item: ChildNode) => {
Using type annotation here is a bad practice, you should rely on typescript

2022-07-13 16:17 UTC, maxineo commented on apps/vanilla/src/components/pagination/pagination.ts
> +  public previous: string | null;
Improve jsdoc

2022-07-13 16:21 UTC, maxineo commented on apps/vanilla/src/components/pagination/paginationContainer.ts
> +    elementList[1].classList.add('active');
Avoid magic numbers

2022-07-13 16:22 UTC, maxineo commented on apps/vanilla/src/components/pagination/paginationContainer.ts
> +    elementList.forEach((item: HTMLElement) => {
No need for type annotations here, typescript is smart enough

2022-07-14 07:06 UTC, elena-dragunova requested changes

2022-07-15 10:05 UTC, timofei-maximov-saritasa requested changes

2022-07-15 10:05 UTC, timofei-maximov-saritasa commented on libs/core/unions/animeType.ts
> +}
Can you explain why do you need these two at the same time?

2022-07-15 10:05 UTC, timofei-maximov-saritasa commented on libs/core/unions/animeType.ts
> +export enum AnimeTypeEnum {
There is no need to write `Enum` in enum name.

2022-07-15 10:49 UTC, EldrAbdr commented on libs/core/unions/animeType.ts
> +}
It was an experiment. And I forgot to choose one of them)

2022-07-15 12:24 UTC, elena-dragunova approved these changes

2022-07-18 08:51 UTC, panov-aleksey-saritasa commented
@EldrAbdr Hi!
1. Please, resolve comments with which you are agree and which you fixed
![image](https://user-images.githubusercontent.com/86595878/179476000-31384370-fbce-43c3-bad7-23938d7e7a4b.png)
2. Please update your `.linting.yml` with:
```yml
name: Linting the code

on:
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        # We need to fetch all branches and commits so that `nx affected` has a base to compare against.
        fetch-depth: 0

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2
      with:
        main-branch-name: 'develop'

    - name: Install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0

    - name: Install dependencies
      run: npm ci

    - name: Lint typescript
      run: npx nx affected --target=lint

    - name: Lint styles
      run: npx nx affected --target=stylelint

```
It should fix dependency installation step. Also, next time don't be silent, please, if you have problems, please, write about them 🙃

2022-07-18 11:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/animeCard.ts
> +   */
Please, format **all** multiline jsdoc comments properly.
```suggestion
  /**
   * Create and initiate an anime card from a template. Return HTML element.
   * @param templateSelector Template selector.
   */
```

2022-07-18 11:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/animeCard.ts
> +        this.airedStart ? this.airedStart.getFullYear() : 'No info'
I suggest moving 'No title', 'タイトルなし', etc. into constants

2022-07-18 11:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/animeTable/tableHeaderButton.ts
> +  public clickHandler: () => void;
Is there a reason that `clickHandler` don't have `readonly`?

2022-07-18 11:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/animeTable/tableHeaderButton.ts
> +      }
Avoid unnecessary nesting. 
```suggestion
      if (item.nodeName !== '#text' && (item as HTMLElement).classList.contains('activated')) {
        (item as HTMLElement).classList.remove('activated');
      }
```

2022-07-18 11:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/api.ts
> +  }
What is the point of `try catch` if you just throwing same error. You can omit it.

2022-07-18 11:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/pagination/paginationCell.ts
> +      return <HTMLElement> this.cell;
Prefer asserting with `as` keyword. Angle bracket syntax can't be used in tsx.

2022-07-18 11:22 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/pagination/paginationContainer.ts
> +  public renderPagination(elementList: HTMLElement[]): void {
Don't forget to add readonly for arrays.

2022-07-20 05:30 UTC, EldrAbdr commented on apps/vanilla/src/blocks/anime/anime.css
> +  box-shadow: var(--box-shadow-hover-cornflowerblue);
Corrected

2022-07-20 05:31 UTC, EldrAbdr commented on apps/vanilla/src/components/animeCard.ts
> +   */
Done

2022-07-20 05:37 UTC, EldrAbdr commented on apps/vanilla/src/components/animeCard.ts
> +        this.airedStart ? this.airedStart.getFullYear() : 'No info'
Done

2022-07-20 05:37 UTC, EldrAbdr commented on apps/vanilla/src/components/animeTable/tableHeaderButton.ts
> +  public clickHandler: () => void;
Done

2022-07-20 05:37 UTC, EldrAbdr commented on apps/vanilla/src/components/animeTable/tableHeaderButton.ts
> +      }
Done

2022-07-20 05:38 UTC, EldrAbdr commented on apps/vanilla/src/components/api.ts
> +  }
Done

2022-07-20 05:38 UTC, EldrAbdr commented on apps/vanilla/src/components/pagination/paginationCell.ts
> +      return <HTMLElement> this.cell;
Done

2022-07-20 05:38 UTC, EldrAbdr commented on apps/vanilla/src/components/pagination/paginationContainer.ts
> +  public renderPagination(elementList: HTMLElement[]): void {
Add

2022-07-20 09:35 UTC, panov-aleksey-saritasa commented on libs/core/dtos/dateTimeRange.ts
> +export interface DateTimeRange {
Use `Dto` suffix for dto names
```suggestion
export interface DateTimeRangeDto {
```

2022-07-20 09:35 UTC, panov-aleksey-saritasa commented on libs/core/enums/statusType.ts
> +}
Please, avoid numeric enums, they are not type-safe

2022-07-20 09:35 UTC, panov-aleksey-saritasa commented on libs/core/models/anime.ts
> +  public readonly type: string;
I suppose you could use `AnimeType` enum here, right?

2022-07-20 09:35 UTC, panov-aleksey-saritasa commented on libs/core/enums/animeType.ts
> +}
Use `CamelCase` for enums
```suggestion
/** Anime type enum. */
export enum AnimeType {
  TV = 'TV',
  OVA = 'OVA',
  Movie = 'MOVIE',
  Special = 'SPECIAL',
  ONA = 'ONA',
  Music = 'MUSIC',
}
```

2022-07-20 09:35 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/components/api.ts
> +    const response = await axios.get(url);
Pass generic into `get`, otherwise `response` has `any` type
```suggestion
    const response = await axios.get<PaginationDto<AnimeDto>>(url);
```

2022-07-20 09:35 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/blocks/anime/__image/anime__image.css
> +}
Rather than hardcode `width`/`height`, consider using more flexible and robust approach with `min-height(width)`/`max-height(width)`.
We have the section about it in [wiki](https://wiki.saritasa.rocks/frontend/languages/css#dont-set-hardcoded-size)
Also you could check this article https://ishadeed.com/article/defensive-css/, it contains section about hardcoded sizes, but also has some useful advices about css styling overall

2022-07-20 09:35 UTC, panov-aleksey-saritasa commented on libs/core/mappers/pagination.mapper.ts
> +  export function fromDto<T>(dto: PaginationDto<T>): Pagination<T> {
Consider changing this function signature to:
```ts
fromDto<Dto, Model>(dto: PaginationDto<Dto>, mapper<Dto, Model>): Pagination<Model>
```
Right now you have a problem that entites inside `PaginationDto` are not properly mapped to models

2022-07-20 09:35 UTC, panov-aleksey-saritasa commented on libs/core/models/immerable.ts
> -  private readonly [immerable] = true;
Why did you remove it? 🤔

2022-07-20 17:26 UTC, pavelzadorin-saritasa requested changes

2022-07-20 17:26 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/components/pagination/paginationCell.ts
> +    this.label = label;
Use object-way param instead of ordered params: https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#avoid-ordered-params-in-constructorsfunctions
additionally it will help you to reduce duplication of code in descendants: `PaginationNext`, `PaginationPrevious`

2022-07-20 17:26 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/pages/index.html
> +        <th class="anime__image table__cell" scope="row"></th>
if this is a template for a regular table row, then you need to use `td` instead of `th`

2022-07-20 17:26 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/components/api.ts
> +  public async getPagination(url: string): Promise<Pagination<Anime>> {
The main thing you get here is Anime list, pagination is generally an auxiliary thing to simplify the work of the backend. Therefore, the name of the methods should reflect this `getAnimeList` or `getPaginatedAnimeList` if you want to emphasize the presence of pagination

2022-07-20 17:26 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/components/api.ts
> +  public getPaginationWithOffset(offset: number): Promise<Pagination<Anime>> {
the same, this is also getting Anime first of all

2022-07-20 17:26 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/components/api.ts
> +    if (this.urlQuery in AnimeType) {
Is it possible to choose either filtering or sorting? but it should be possible to impose both conditions, let's discuss how this can be done.

2022-07-21 13:13 UTC, danilkukryakov requested changes

2022-07-21 13:13 UTC, danilkukryakov commented on apps/vanilla/src/components/pagination/paginationCell.ts
> +  private checkForUndefinedChild(): void {
This function's name seems misleading to me, let's improve it.
Usually we expect a function with `check` in it's name to check the condition and return the result (true/false). So such function has single responsibility.
In your case you have additional action if condition is satisfied. So your function has two responsibilities. Moreover, the side-effect of this check is not documented.
As far as I can understand, the purpose of this function is to remove child node on some condition. Maybe we can adjust your function like this:
```ts
public setEventListener(): void {
  this.cell?.addEventListener('click', () => {
    // ...
    this.removeIfTextNode(this.cell);
   // ...
  })
}

// I'm not sure if this name makes sense in your context. So select more appropriate if necessary.
private removeIfTextNode(cell: HTMLElement): void {
  const element = cell.parentNode?.firstChild;
  if (element?.nodeName === '#text') {
    element.remove();
  }
}
```

Also I have another concern about this function but I'm not sure. To me it seems a bit tricky that the element (this.cell) can remove itself if it was clicked. I suppose, it may cause unexpected behaviour in some cases. Please, be sure to check the implementation again. Maybe you will come up with better solution.

2022-07-21 13:13 UTC, danilkukryakov commented on apps/vanilla/src/components/pagination/paginationContainer.ts
> +  public itemsPerPage: number;
If I'm not mistaken it's impossible to change `itemsPerPage` in your app. So let's make this field `readonly`.

2022-07-21 13:13 UTC, danilkukryakov commented on apps/vanilla/src/pages/index.html
> +    </footer>
Do we need this empty footer? Let's remove it if we don't need it.

2022-07-25 11:20 UTC, EldrAbdr commented on apps/vanilla/src/components/animeCard.ts
> +  public readonly titleJpn: string;
Corrected

2022-07-25 11:20 UTC, EldrAbdr commented on libs/core/enums/statusType.ts
> +}
Corrected

2022-07-25 11:21 UTC, EldrAbdr commented on libs/core/models/anime.ts
> +  public readonly type: string;
Corrected

2022-07-25 11:21 UTC, EldrAbdr commented on libs/core/enums/animeType.ts
> +}
Corrected

2022-07-25 11:51 UTC, EldrAbdr commented on libs/core/mappers/pagination.mapper.ts
> +  export function fromDto<T>(dto: PaginationDto<T>): Pagination<T> {
Corrected

2022-07-25 11:51 UTC, EldrAbdr commented on apps/vanilla/src/blocks/anime/__image/anime__image.css
> +}
Corrected

2022-07-25 11:51 UTC, EldrAbdr commented on apps/vanilla/src/components/api.ts
> +    const response = await axios.get(url);
Corrected

2022-07-25 11:54 UTC, EldrAbdr commented on libs/core/models/immerable.ts
> -  private readonly [immerable] = true;
I don't know how it happened. Maybe IDE was offered. restored

2022-08-06 08:19 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-10 11:40 UTC, chernodub requested changes

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/components/constants/constants.ts
> +const BASE_URL = 'https://api.camp-js.saritasa.rocks/api/v1/anime/anime';
Usually, we prefer to use `.env` files to store such information. Consider an example, your application usually has several "environments" e.g: production, development. When you're working on an application, you won't likely to want to mess with the data of the users in your app, but instead, talk to an API that serves some "data for testing". That's why you need multiple environments. So, handling multiple environments in "constants" files is usually tiresome, since you'd need to figure out how to swap those files depending on an environment.

Vite already gives you the ability to easily handle env files https://vitejs.dev/guide/env-and-mode.html

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/components/pagination/paginationCell.ts
> +  isDisable?: boolean;
[Usually, when we don't mutate the data, we prefer making it `readonly`](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#promote-immutability)

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/components/pagination/paginationCell.ts
> +    ) as HTMLTemplateElement;
I see that your pagination template is [not inside the table](https://github.com/saritasa-nest/camp-js-2022-eldar-abdrahmanov/pull/1/files#diff-12b92b7a0e4fd3f4d9ab0c59a1af2ecc8b5ec261cce98aca7b8368df9a96aec7R28-R32). So, why is it a `cell`?

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/components/api.ts
> +    this.urlParams = new URLSearchParams('offset=0');
The main benefit of using the `URLSearchParams` is that you can abstract yourself from creating url string, since this approach is not mistypings-prone. So, I recommend using an object instead of string here
```ts
const params = new URLSearchParams({param: 1, param2: 2});

console.log(params.get('param2')) // prints '2'
```

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/components/pagination/paginationCell.ts
> +      this.removeIfTextNode();
It is not clear, why do you remove the element if it has a cell? Please always specify the implicit logic via documentation. [Be explicit](https://wiki.saritasa.rocks/frontend/practices/code#be-explicit)

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/components/pagination/paginationCell.ts
> +    this.cell?.addEventListener('click', () => {
Please [use buttons for handling clicks](https://wiki.saritasa.rocks/frontend/languages/html#use-button-for-handling-user-clicks)

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/components/pagination/paginationCell.ts
> +      const paginationButton = paginationCell.querySelector('.page-link');
Since you've created a global `getElement` util, please stick to using it everywhere

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +        <tr class="table__head">
You've used `table`-related element, but there is no `table` block. You can't make it that way. Please revise the BEM approach, I recommend to check out [this cheatsheet](https://9elements.com/bem-cheat-sheet/)

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +    <template class="anime-template table__cell">
I'd recommend thinking about the name of your class names here. It could not be a `cell` since it's a parent of the row

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/pages/index.ts
> +import 'bootstrap/dist/css/bootstrap.min.css';
@golovachev-yaroslav please always specify **why**

2022-08-10 11:40 UTC, chernodub commented on libs/core/mappers/pagination.mapper.ts
> +      previous: dto.previous,
Do you ever use `next` and `previous`? If no, consider omitting the information you don't use from your domain model

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/pages/index.ts
> +  const offset = indexOfCell * limitAnimeOnPage;
Consider calculating such stuff inside the API class to unload your main script and remove [code duplication](https://github.com/saritasa-nest/camp-js-2022-eldar-abdrahmanov/pull/1/files#diff-f7dc479a37277ce950337c61b99013f6fc73c255bc2d6ad4834674da410e77abR73-R74)

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/pages/index.ts
> +    // Condition for defining the previous button
Please avoid obvious comments in your code. Having such stuff in your code makes you support x2 amount of code

2022-08-10 11:40 UTC, chernodub commented on apps/vanilla/src/pages/index.ts
> +      );
Since you're relying on a specific indexes here, consider moving this code out of the loop to generalize the logic. The same for last index

2022-08-29 07:57 UTC, closed without merging