feat add anime-table component and anime service #JS19-399
saritasa-nest/camp-js-2022-eldar-abdrahmanov pull request #4
Opened 2022-07-25 11:32 UTC by EldrAbdr

2022-07-26 05:52 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-26 05:52 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public animeList$: Observable<readonly Anime[]>;
Don't forget to add `readonly` modifier.

2022-07-26 05:52 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +  }
Empty constructor can be removed

2022-07-26 05:52 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +  public constructor(private httpClient: HttpClient) {}
Add `readonly` modifier to dependency

2022-07-26 07:42 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +      <img class="anime-image" [src]="row.imageUrl" alt="" />
Missing alt

2022-07-26 07:42 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public constructor(private animeService: AnimeService) {
If you are not using `animeService` outside of your constructor, you can omit `private`, otherwise don't forget to add `readonly`. You can read more [here](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties)

2022-07-26 07:42 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +  aria-label="anime-table"
Missing `trackBy`
https://material.angular.io/cdk/table/overview#trackby
https://angular.io/api/core/TrackByFunction

2022-07-28 13:50 UTC, panov-aleksey-saritasa commented on apps/angular/project.json
> +        ]
Mistake on our part, please, replace `react` with `angular` 🙃

2022-07-28 13:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +          PaginationMapper.fromDto<AnimeDto, Anime>(dto, AnimeMapper.fromDto)),
In some cases TypeScript could do type inference for generics based on passed arguments
I recommend you to read: https://www.typescriptlang.org/docs/handbook/2/generics.html#handbook-content
```suggestion
          PaginationMapper.fromDto(dto, AnimeMapper.fromDto)),
```

2022-07-28 13:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +      .get<PaginationDto<AnimeDto>>(environment.baseUrl, { params: parameters })
FYI, you could reduce the code a bit by renaming `parameters` to `params`
```suggestion
    const params = new HttpParams()
      .set('ordering', 'id');
    return this.httpClient
      .get<PaginationDto<AnimeDto>>(environment.baseUrl, { params })
```

2022-07-28 13:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +  }
Please, don't forget to check out SonarCloud's comments. Sometimes it makes good remarks🙂

2022-07-28 13:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/app.component.html
> +<anime></anime>
Since you already have the lecture about rouing in Angular, consider revising your approach. Consider binding anime page to some specific route. If you have some problems you could check this article: https://angular.io/guide/router

2022-08-03 06:26 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public animeList$: Observable<readonly Anime[]>;
Added

2022-08-03 06:27 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/anime.component.ts
> +  }
removed

2022-08-03 06:27 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +      <img class="anime-image" [src]="row.imageUrl" alt="" />
added

2022-08-03 06:28 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +  aria-label="anime-table"
TrackBy added

2022-08-03 06:28 UTC, EldrAbdr commented on apps/angular/project.json
> +        ]
Replaced

2022-08-03 13:11 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  ];
Let's add `as const` to improve type safety:
```ts
public readonly displayedColumns = [
  'image',
  'titleEng',
  // ...
] as const;
```

2022-08-04 02:22 UTC, thanhnguyen-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +import { AnimeService } from '../../../../../core/services/anime.service';
Could we use the import parth by "@js-camp"?
I see it will be better

2022-08-04 08:44 UTC, timofei-maximov-saritasa requested changes
Anime-related logic should be located in standalone module, please check task description

2022-08-08 09:29 UTC, EldrAbdr commented on apps/angular/src/app/app.module.ts
> +import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
Done

2022-08-08 09:31 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +import { AnimeService } from '../../../../../core/services/anime.service';
Linter won't let me do it. 
"3:1  error  Projects should use relative imports to import from other files within the same project. "

2022-08-09 16:06 UTC, thanhnguyen-saritasa approved these changes

2022-08-10 01:30 UTC, pavel-romanov8 requested changes

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/project.json
> +        ]
Not sure how it was resolved, because i still see the `react` in the path. Please, resolve the comments only after you push your updated code to the repo

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.css
> +  max-height: 150px;
Let's move those values to a CSS custom properties, because we already used them in the vanilla part and, I believe, will use in the React

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.css
> +  border: 1px white solid;
Prefer, using custom properties for colors

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +    <td mat-cell *matCellDef="let row">{{ row.titleEng }}</td>
Let's give it a meaningful name, instead of just `row`. As I understand, you are referring to anime here. If that is the case, then we could improve the naming to `let anime`

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +
Redundant empty line

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +/** Anime service to interact with API. */
Please, check the [architecture section](https://wiki.saritasa.rocks/frontend/frameworks/architecture/) in our wiki. We are not directly saying that the service works with API, instead we are encapsulating such knowledge and service clients work with it like with _domain service_ without knowing a thing about its inner implementation. So, there is no need to say that the service works with some third party API

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/environments/environment.ts
> +  baseUrl: 'https://api.camp-js.saritasa.rocks/api/v1/anime/anime/',
It is not really a `baseUrl` because it can't be used in every request to the API. It should be `https://api.camp-js.saritasa.rocks/api/v1/` instead

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +  public getAnimeList(): Observable<readonly Anime[]> {
Please, don't force function clients to work with immutable data, they should decide on their own what they want to do with it
```suggestion
  public getAnimeList(): Observable<Anime[]> {
```

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public trackBy(index: number, item: Anime): number {
If we are not using some function arguments instead of a name, we are leaving a lower dash `_`
```suggestion
  public trackBy(_: number, item: Anime): number {
```

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +  *ngIf="animeList$ | async as animeList"
If there is no anime list, what will the user see? Is it just a blank page?

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +   * @param index Serial number.
It is not a serial number, but the index of anime in an array

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +   * Return index of item.
It doesn't return any index. The `trackBy` function is meant to track items in the array by specified key

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +   * Return index of item.
Also, if you want to somehow document return statement, prefer using `@returns`. It makes your intentions more explicit

2022-08-10 01:30 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +  /** Makes a request to the API and returns a list of anime. */
As i already said, we should describe the inners of entities and functions

2022-08-10 05:31 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.css
> +  max-height: 150px;
Values moved to the CSS custom properties.

2022-08-10 05:32 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.css
> +  border: 1px white solid;
Variable created

2022-08-10 05:33 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +    <td mat-cell *matCellDef="let row">{{ row.titleEng }}</td>
"Row" renamed to "anime"

2022-08-10 05:33 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +
Removed

2022-08-10 05:34 UTC, EldrAbdr commented on apps/angular/src/core/services/anime.service.ts
> +/** Anime service to interact with API. */
Corrected

2022-08-10 05:34 UTC, EldrAbdr commented on apps/angular/src/environments/environment.ts
> +  baseUrl: 'https://api.camp-js.saritasa.rocks/api/v1/anime/anime/',
Corrected

2022-08-10 05:34 UTC, EldrAbdr commented on apps/angular/src/core/services/anime.service.ts
> +  public getAnimeList(): Observable<readonly Anime[]> {
Readonly removed

2022-08-10 05:35 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public trackBy(index: number, item: Anime): number {
Corrected

2022-08-10 05:35 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +  *ngIf="animeList$ | async as animeList"
Add loading spinner

2022-08-10 05:36 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +   * @param index Serial number.
Corrected

2022-08-10 05:37 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +   * Return index of item.
Corrected

2022-08-10 05:37 UTC, EldrAbdr commented on apps/angular/src/core/services/anime.service.ts
> +  /** Makes a request to the API and returns a list of anime. */
Corrected

2022-08-11 07:50 UTC, chernodub approved these changes

2022-08-11 07:50 UTC, chernodub commented on libs/core/models/pagination.ts
> +  public readonly results: T[];
I believe there is no reason to make it mutable. I don't see you ever mutate your array. In our practice, [we like to keep things immutable](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#promote-immutability)

2022-08-11 15:03 UTC, dbitkovski approved these changes

2022-08-11 15:03 UTC, dbitkovski commented on apps/angular/src/app/app-routing.module.ts
> +  providers: [{ provide: HashLocationStrategy, useClass: HashLocationStrategy }],
Get used to commenting unusual things. It helps developers to understand why it was done :)

2022-08-11 15:03 UTC, dbitkovski commented on apps/angular/src/index.html
> +</head>
Formatting issue

2022-08-29 08:00 UTC, closed without merging