Feature/js19 411 angular list management
saritasa-nest/camp-js-2022-eldar-abdrahmanov pull request #5
Opened 2022-08-03 05:39 UTC by EldrAbdr

2022-08-04 09:07 UTC, timofei-maximov-saritasa requested changes

2022-08-04 09:07 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/components/filtering/filtering.component.ts
> +  @Output() private readonly filteringEventEmitter: EventEmitter<MatSelectChange>;
Also, `filteringEventEmitter` is not a good name for your `output`. There is no need in `EventEmitter` suffix. 
For example, `filterChange`.

2022-08-04 09:07 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    this.route.queryParamMap.subscribe(param => {
https://wiki.saritasa.rocks/frontend/frameworks/angular/best-practices#do-not-subscribe-inside-a-constructor

2022-08-04 09:07 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/components/pagination/pagination.component.ts
> +    this.showFirstLastButtons = true;
These can be set outside of constructor

2022-08-05 08:49 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-08 12:15 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +    <div class="anime-search__container">
Redone

2022-08-08 12:16 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/filtering/filtering.component.ts
> +    this.animeTypeList = Object.values(AnimeType);
Done

2022-08-08 12:16 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/filtering/filtering.component.ts
> +  @Output() private readonly filteringEventEmitter: EventEmitter<MatSelectChange>;
Redone

2022-08-08 12:16 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/pagination/pagination.component.ts
> +    this.showFirstLastButtons = true;
Done

2022-08-08 12:17 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    this.route.queryParamMap.subscribe(param => {
Changed

2022-08-08 12:18 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.css
> +  color: white;
Variable created

2022-08-08 12:18 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +        aria-label="Enter anime title"
Done

2022-08-08 12:19 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +        <img class="table-image" [src]="row.imageUrl" alt="anime preview" />
As alt is now the name of the anime.

2022-08-08 17:53 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    this.directionSortHeader = '';
You can set the initial value '' above, when you define a variable.

2022-08-08 17:53 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    this.pagination$ = new BehaviorSubject<PaginationUrlParams>({
Let's move out the initialization from constructor to some private function, it makes constructor more readable.

2022-08-08 17:53 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    this.route.queryParamMap.subscribe(param => {
Try to avoid extra subscription and restructure your code, there isn't need to subscribe for queryParamMap, you can start from this stream and then using switchMap to get anime list. If you need help, you can write me in slack.

2022-08-10 04:06 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    this.directionSortHeader = '';
Done

2022-08-10 04:06 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    this.route.queryParamMap.subscribe(param => {
Redone

2022-08-10 04:07 UTC, EldrAbdr commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    this.pagination$ = new BehaviorSubject<PaginationUrlParams>({
Moved to a separate function

2022-08-12 04:40 UTC, panov-aleksey-saritasa requested changes

2022-08-12 04:40 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  /** A lifecycle hook. */
You could use [@inheritdoc](https://jsdoc.app/tags-inheritdoc.html) jsdoc tag for angular hooks
```suggestion
  /** @inheritdoc */
```

2022-08-12 04:40 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  private sorting$!: BehaviorSubject<Sort>;
Please, avoid using the `!`  non-null assertion, it's unsafe. Usually we initialize either in the constructor or right away on a single line

2022-08-12 04:40 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public getAnimeList(): void {
Actually this method does not subscribe to anything, it just initialize `animeList$` property

2022-08-12 04:40 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public getAnimeList(): void {
Like I said before, please, initialize class properties either right away or in the constructor. You improve your code readability this way, since readers of your code wouldn't have to seach throughout your class to find where property is initialized + you wouldn't have to use some hacks like `!` non null assertion

2022-08-12 04:40 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public getAnimeList(): void {
To keep constructor as simple as possible, you move out creation stuff into a function
```ts
// you constructor, for example
this.animeList$ = this.initAnimeListStream();

private initAnimeListStream() {
  return this.route.queryParamMap.pipe(
  ...
}
```

2022-08-12 04:40 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +        return this.animeService.getPaginationAndAnimeList(httpParams).pipe(
Your UI layer should not know anything about http params, UI should collect data from user inputs and then send them to services and services then maps data from passed from UI to needed format (httpParams in your case). Consider revising your approach

2022-08-12 04:40 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public handlePaginationClick(event: PageEvent): void {
On angular projects we use `on` prefix for event handler names
```suggestion
   * Handle actions with pagination.
   * @param event Event received from Pagination component.
   */
  public onPaginationClick(event: PageEvent): void {
```

2022-08-12 04:40 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/filtering/filtering.component.ts
> +  @Output() private readonly filterChange = new EventEmitter();
```suggestion
  /** Filtering event emitter. */
  @Output()
  private readonly filterChange = new EventEmitter();
```

2022-08-29 08:00 UTC, closed without merging